version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    container_name: kanboard
    ports:
      - "8080:80"
#      - "4443:443"
    environment:
      DATABASE_URL: mysql://kanboard:dXZnv6Rn9mA8@192.168.10.2:3306/kanboard
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
