version: '3.8'

x-envionment:
  proxy:
    &proxy
    CADDY_INGRESS_NETWORKS: public

services:
  caddy:
    image: ghcr.io/alflag-team/caddy-cloudflare:latest
    ports:
     - 80:80
     - 443:443
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /mnt/shared/caddy/data:/data
    networks:
     - public
    environment:
      <<: *proxy
    deploy:
      labels:
        caddy.email: support@alflag.org
      placement:
        constraints:
         - node.role == manager
      resources:
        reservations:
          cpus: '0.1'
          memory: 200M

networks:
  public:
    external: true
