version: '3.8'

x-envionment:
  caddy:
    &caddy
    CADDY_INGRESS_NETWORKS: public
  label:
    &label
    caddy.email: support@alflag.org

services:
  caddy:
    image: ghcr.io/alflag-team/caddy-cloudflare:latest
    ports:
      - published: 80
        target: 80
        protocol: tcp
        mode: ingress
      - published: 443
        target: 443
        protocol: tcp
        mode: ingress
    networks:
     - public
    volumes:
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
      - type: bind
        source: "/mnt/shared/caddy/data"
        target: "/data"
    environment:
      <<: *caddy
    deploy:
      labels:
        <<: *label
      placement:
        constraints:
         - node.role == manager
      resources:
        reservations:
          cpus: '0.1'
          memory: 200M

networks:
  public:
    external: true
