#cloud-config
users:
  - default
  - name: infra
    groups: [sudo]
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    lock_passwd: true

package_update: true
packages:
  - qemu-guest-agent
