version: '3.3'

services:
  agent:
    image: swarmpit/agent:latest
    environment:
      DOCKER_API_VERSION: '1.35'
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - local
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
      resources:
        reservations:
          memory: 32M
        limits:
          memory: 64M

  app:
    image: swarmpit/swarmpit:latest
    healthcheck:
      test:
       - CMD
       - curl
       - -f
       - http://localhost:8080
      interval: 60s
      timeout: 10s
      retries: 3
    environment:
      SWARMPIT_DB: http://couchdb:5984
      SWARMPIT_INFLUXDB: http://influxdb:8086
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - public
     - local
    deploy:
      labels:
        caddy: swarmpit.sys.alflag.org
        caddy.reverse_proxy: '{{upstreams 8080}}'
      placement:
        constraints:
         - node.role == manager
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 1024M

  couchdb:
    image: treehouses/couchdb:2.3.1
    volumes:
     - /mnt/shared/swarmpit/couchdb-data:/opt/couchdb/data
    networks:
     - local
    deploy:
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M

  influxdb:
    image: influxdb:1.7
    volumes:
     - /mnt/shared/swarmpit/influx-data:/var/lib/influxdb
    networks:
     - local
    deploy:
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M

networks:
  public:
    external: true
  local:
    driver: overlay
