version: '3.8'

x-envionment:
  db:
    &db
    POSTGRES_HOST: db
    POSTGRES_DATABASE: weblate
    POSTGRES_USER: weblate
    POSTGRES_PASSWORD: "CHANGE_ME"
    POSTGRES_PORT: 5432
  cache:
    &cache
    REDIS_HOST: cache
    REDIS_PORT: 6379
  weblate:
    &weblate
    WEBLATE_EMAIL_HOST: smtp.gmail.com
    WEBLATE_EMAIL_PORT: 587
    WEBLATE_EMAIL_USE_SSL: 0
    WEBLATE_EMAIL_USE_TLS: 1
    WEBLATE_EMAIL_HOST_USER: ${WEBLATE_EMAIL_HOST_USER}
    WEBLATE_EMAIL_HOST_PASSWORD: ${WEBLATE_EMAIL_HOST_PASSWORD}
    WEBLATE_SERVER_EMAIL: no-reply@alflag.org
    WEBLATE_DEFAULT_FROM_EMAIL: no-reply@alflag.org
    WEBLATE_SITE_DOMAIN: translate.alflag.org
    WEBLATE_ADMIN_PASSWORD: ${WEBLATE_ADMIN_PASSWORD}
    WEBLATE_ADMIN_NAME: ${WEBLATE_ADMIN_NAME}
    WEBLATE_ADMIN_EMAIL: ${WEBLATE_ADMIN_EMAIL}
    WEBLATE_GITHUB_USERNAME: ${WEBLATE_GITHUB_USERNAME}
    WEBLATE_GITHUB_TOKEN: ${WEBLATE_GITHUB_TOKEN}
    WEBLATE_AUTO_UPDATE: "true"
    WEBLATE_SITE_TITLE: "Alflag Translate"
    WEBLATE_DEFAULT_COMMITER_NAME: Alflag
    WEBLATE_DEFAULT_COMMITER_EMAIL: admin@alflag.org
  caddy:
    CF: &CADDY_CF "cloudflare CHANGE_ME"

services:
  weblate:
    image: weblate/weblate
    restart: always
    networks:
      - local
      - public
    volumes:
      - type: bind
        source: "/mnt/shared/weblate/data"
        target: "/app/data"
      - type: tmpfs
        target: "/app/cache"
    environment:
      <<: [*db, *cache, *weblate]

  db:
    image: postgres:14-alpine
    restart: always
    networks:
      - local
    volumes:
      - type: bind
        source: "/mnt/shared/weblate/db"
        target: "/var/lib/postgresql/data"
    environment:
      <<: *db

  cache:
    image: redis:6-alpine
    restart: always
    command: [redis-server, --save, '60', '1']
    networks:
      - local
    volumes:
      - type: bind
        source: "/mnt/shared/weblate/cache"
        target: "/data"

networks:
  public:
    external: true
  local:
    driver: overlay
