version: "3"

services:
  infrared:
    image: haveachin/infrared:latest
    stdin_open: true
    tty: true
    ports:
      - 25565:25565/tcp
    volumes:
      - /mnt/shared/infrared/configs:/configs
    environment:
      INFRARED_CONFIG_PATH: "/configs"
      INFRARED_RECEIVE_PROXY_PROTOCOL: "true"
    networks:
     - public
    deploy:
      placement:
        constraints:
         - node.role == worker

networks:
  public:
    external: true
