version: '3.8'

services:
  proxy:
    image: viasnake/infrared-arm64:latest
    environment:
      INFRARED_CONFIG_PATH: /configs
    ports:
      - published: 25565
        target: 25565
        protocol: tcp
        mode: ingress
    networks:
     - public
    volumes:
      - type: bind
        source: "/mnt/shared/infrared/configs"
        target: "/configs"
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 2
        constraints:
         - node.role == worker

networks:
  public:
    external: true
