version: '3.9'

services:
  proxy:
    image: viasnake/infrared-arm64:latest
    environment:
      INFRARED_CONFIG_PATH: /configs
    ports:
     - 25565:25565
    volumes:
     - /mnt/shared/infrared/configs:/configs
    networks:
     - public
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 2
        constraints:
         - node.role == worker

networks:
  public:
    external: true
