version: '3.3'

services:
  infrared:
    image: ghcr.io/viasnake/infrared-arm64:latest
    tty: true
    environment:
      INFRARED_CONFIG_PATH: /configs
    volumes:
     - /mnt/shared/infrared:/configs
    networks:
     - public
    deploy:
      mode: global
      placement:
        constraints:
         - node.role == worker

networks:
  public:
    external: true
