version: '3.3'

services:
  infrared:
    image: ghcr.io/viasnake/infrared-arm64:latest
    tty: true
    environment:
      INFRARED_CONFIG_PATH: /configs
      INFRARED_RECEIVE_PROXY_PROTOCOL: 'true'
    volumes:
     - /mnt/configs:/configs
    networks:
     - public
    deploy:
      labels:
        caddy: :25565
        caddy.reverse_proxy: '{{upstreams 25565}}'

networks:
  public:
    external: true
