version: "3"

services:
  infrared:
    image: haveachin/infrared:latest
    stdin_open: true
    tty: true
    volumes:
      - /mnt/shared/infrared/configs:/configs
    environment:
      INFRARED_CONFIG_PATH: "/configs"
      INFRARED_RECEIVE_PROXY_PROTOCOL: "true"
    networks:
     - public
    deploy:
      labels:
        caddy: ${HOSTNAME}
        caddy.reverse_proxy: '{{upstreams 25565}}'

networks:
  public:
    external: true
