version: '3.8'

services:
  db:
    image: postgres:11-alpine
    networks:
     - local
    volumes:
      - type: bind
        source: "/mnt/shared/docs/postgresql-data"
        target: "/var/lib/postgresql/data"
    environment:
        DB_TYPE: postgres
        DB_HOST: db
        DB_PORT: 5432
        DB_USER: &db_user wikijs
        DB_PASS: &db_password ${DB_PASSWORD}
        DB_NAME: &db wiki

  wiki:
    image: ghcr.io/requarks/wiki:2
    networks:
     - public
     - local
    environment:
      POSTGRES_DB: *db
      POSTGRES_PASSWORD: *db_password
      POSTGRES_USER: *db_user
    deploy:
      labels:
        caddy: docs.alflag.org
        caddy.reverse_proxy: "{{upstreams 3000}}"
        caddy.tls.dns: "cloudflare ${CF_API_TOKEN}"

networks:
  public:
    external: true
  local:
    driver: overlay
