version: '3.8'

x-envionment:
  db:
    &db
    POSTGRES_DB: &db wiki
    POSTGRES_PASSWORD: &db_password ${DB_PASSWORD}
    POSTGRES_USER: &db_user wikijs
  wiki:
    &wiki
    DB_TYPE: postgres
    DB_HOST: db
    DB_PORT: 5432
    DB_USER: *db_user
    DB_PASS: *db_password
    DB_NAME: *db
  label:
    &label
    caddy: docs.alflag.org
    caddy.reverse_proxy: "{{upstreams 3000}}"
    caddy.tls.dns: "cloudflare ${CF_API_TOKEN}"

services:
  db:
    image: postgres:11-alpine
    networks:
     - local
    volumes:
      - type: bind
        source: "/mnt/shared/docs/postgresql-data"
        target: "/var/lib/postgresql/data"
    environment:
      <<: *db

  wiki:
    image: ghcr.io/requarks/wiki:2
    networks:
     - public
     - local
    environment:
      <<: *wiki
    deploy:
      labels:
        <<: *label

networks:
  public:
    external: true
  local:
    driver: overlay
