version: '3.8'

x-envionment:
  db:
    &db
    POSTGRES_DB: &DB wiki
    POSTGRES_PASSWORD: &PASSWORD "CHANGE_ME"
    POSTGRES_USER: &USER wikijs
  wiki:
    &wiki
    DB_TYPE: postgres
    DB_HOST: db
    DB_PORT: 5432
    DB_USER: *USER
    DB_PASS: *PASSWORD
    DB_NAME: *DB
  label:
    &label
    caddy: docs.alflag.org
    caddy.reverse_proxy: "{{upstreams 3000}}"
    caddy.tls.dns: "cloudflare CHANGE_ME"

services:
  db:
    image: postgres:11-alpine
    networks:
     - local
    volumes:
      - type: bind
        source: "/mnt/shared/docs/postgresql-data"
        target: "/var/lib/postgresql/data"
    environment:
      <<: *db

  wiki:
    image: ghcr.io/requarks/wiki:2
    networks:
     - public
     - local
    environment:
      <<: *wiki
    deploy:
      labels:
        <<: *label

networks:
  public:
    external: true
  local:
    driver: overlay
