version: '3'

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: "CHANGE_ME"
      POSTGRES_USER: wikijs
    logging:
      driver: 'none'
    networks:
     - local
    volumes:
      - type: bind
        source: "/mnt/shared/docs/postgresql-data"
        target: "/var/lib/postgresql/data"

  wiki:
    image: ghcr.io/requarks/wiki:2
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: "CHANGE_ME"
      DB_NAME: wiki
    networks:
     - public
     - local
    deploy:
      labels:
        caddy: docs.alflag.org
        caddy.reverse_proxy: '{{upstreams 3000}}'
        caddy.tls.dns: 'cloudflare {env.CF_API_TOKEN}'

networks:
  public:
    external: true
  local:
    driver: overlay
