---
database:
  hosts:
    database1003:
      ansible_host: 10.210.4.3

monitor:
  hosts:
    monitor1002:
      ansible_host: 10.210.2.2

minecraftv2:
  hosts:
    minecraft1001:
      ansible_host: 10.210.30.1
    minecraft1002:
      ansible_host: 10.210.30.2

minecraftpanel:
  hosts:
    minecraftpanel1001:
      ansible_host: 10.210.30.31

minecraftproxy:
  hosts:
    minecraftproxy1001:
      ansible_host: 10.210.30.101

admin.general:
  hosts:
    admin100:
      ansible_host: 10.210.2.1
    admin101:
      ansible_host: 10.210.10.1

dns.unbound:
  hosts:
    dns100:
      ansible_host: 10.210.2.240
    dns101:
      ansible_host: 10.210.2.241

web.general:
  hosts:
    web100:
      ansible_host: 10.210.2.5
    web101:
      ansible_host: 10.210.2.6

# web.ptero-panel:
#   hosts:
#     web000:
#       ansible_host:

app.general:
  hosts:
    app100:
      ansible_host: 10.210.2.9

game.ptero-node:
  hosts:
    game100:
      ansible_host: 10.210.2.8

zabbix.general:
  hosts:
    zabbix100:
      ansible_host: 10.210.2.250

cache.redis:
  hosts:
    cache100:
      ansible_host: 10.210.2.10
